version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
